---
apiVersion: v1
kind: ReplicationController
metadata:
  name: e-rate-api
  namespace: default
spec:
  replicas: 1
  selector:
    app: e-rate-api
  template:
    metadata:
      name: e-rate-api
      labels:
        app: e-rate-api
      namespace: default
    spec:
      containers:
      - name: e-rate-api
        image: hub.docker.gemii.cc:7443/lizcloud/e-rate-api:latest
        imagePullPolicy: Always
        ports:
        - name: server-port
          containerPort: 9815
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: development
      imagePullSecrets:
      - name: dev-sec