eureka:
  client:
    serviceUrl:
      #defaultZone: http://peer2:8762/eureka/,http://peer1:8761/eureka/
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true #将IP注册到eureka上 服务(容器)之间互相调用是通过 application name 匹配到一个或者多个IP 然后负载均衡

server:
  port: 8763

spring:
  application:
      name: settlement-core
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: com.lsj.settlement.config.MySQLUpperCaseStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://192.168.2.193:3306/lz.settlement?useSSL=false&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver